version: '3.9'

services:
  web:
    build: .
    container_name: medibook-web
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py loaddata fixtures/initial_data.json || true &&
        python manage.py collectstatic --noinput &&
        python add_medecins.py || true &&
        gunicorn medibook_project.wsgi:application --bind 0.0.0.0:7009 --workers 3
      "
    ports:
      - "7009:7009"
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: "ton_secret_key"
      DEBUG: "False"
      DATABASE_URL: "postgres://medibook_user:medibook_pass@db:5432/medibook_db"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - medibooknet

  db:
    image: postgres:15
    container_name: medibook-db
    environment:
      POSTGRES_DB: medibook_db
      POSTGRES_USER: medibook_user
      POSTGRES_PASSWORD: medibook_pass
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - medibooknet

volumes:
  db_data:
  static_volume:
  media_volume:

networks:
  medibooknet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16