services:
  web:
    build: .
    restart: always
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py loaddata fixtures/initial_data.json || true &&
        python add_medecins.py || true &&
        python manage.py collectstatic --noinput &&
        gunicorn medibook_project.wsgi:application --bind 0.0.0.0:7009 --workers 3
      "
    ports:
      - "7009:7009"
    depends_on:
      - db
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      DEBUG: "False"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "db"
      DB_PORT: "${DB_PORT}"
      ALLOWED_HOSTS: "${ALLOWED_HOSTS}"
      CSRF_TRUSTED_ORIGINS: "${CSRF_TRUSTED_ORIGINS}"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      medibook_net:
        ipv4_address: 10.50.0.10

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      medibook_net:
        ipv4_address: 10.50.0.11

volumes:
  db_data:
  static_volume:
  media_volume:

networks:
  medibook_net:
    name: medibook_net_custom
    driver: bridge
    ipam:
      config:
        - subnet: 10.50.0.0/24