# Generated by Django 5.2.14 on 2026-05-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orientation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialite',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='specialite',
            name='icone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
