# Generated by Django 5.1 on 2026-05-12 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('rendez_vous', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='appointments.rendezvous')),
            ],
        ),
    ]
