# Generated by Django 5.2.14 on 2026-05-31 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orientation', '0001_initial'),
        ('appointments', '0002_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='specialite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_orientation.specialite'),
        ),
    ]
