# Generated by Django 6.0.5 on 2026-05-09 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Spécialités',
            },
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_professionnel', models.CharField(blank=True, max_length=20)),
                ('adresse_cabinet', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('annees_experience', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='medecins/')),
                ('est_actif', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('specialite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.specialite')),
            ],
            options={
                'verbose_name_plural': 'Médecins',
            },
        ),
    ]
