# Generated by Django 5.2.14 on 2026-05-31 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orientation', '0001_initial'),
        ('appointments', '0003_alter_rendezvous_specialite'),
        ('doctors', '0002_avis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='specialite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecins_doctors', to='ai_orientation.specialite'),
        ),
        migrations.AlterModelOptions(
            name='medecin',
            options={},
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='adresse_cabinet',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='annees_experience',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='description',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='est_actif',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='photo',
        ),
        migrations.AlterField(
            model_name='medecin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medecin_doctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Specialite',
        ),
    ]
