# Generated by Django 5.2.14 on 2026-05-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_medecin_specialite_alter_medecin_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='telephone_professionnel',
        ),
        migrations.AddField(
            model_name='medecin',
            name='telephone',
            field=models.CharField(default='Non renseigné', max_length=20),
        ),
    ]
